# -*- coding: utf-8 -*-
editor.replace("ĉ", "¢")
editor.replace("ĝ", "ð")
editor.replace("ĥ", "×")
editor.replace("ĵ", "þ")
editor.replace("ŝ", "§")
editor.replace("ŭ", "µ")
editor.replace("Ĉ", "¥")
editor.replace("Ĝ", "Ð")
editor.replace("Ĥ", "÷")
editor.replace("Ĵ", "Þ")
editor.replace("Ŝ", "¬")
editor.replace("Ŭ", "¤")

notepad.menuCommand(MENUCOMMAND.EDIT_SELECTALL)
notepad.menuCommand(MENUCOMMAND.EDIT_COPY)

notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)
notepad.menuCommand(MENUCOMMAND.EDIT_UNDO)